title: Avalonstar
author: Bryan Veloso

root: /
permalink: /journal/:year/:title/
date_format: 'ordinal'

source: _source
destination: _public
plugins: plugins
markdown: kramdown
pygments: false
paginate: 10
pagination_dir: journal
titlecase: true  # Converts page and post titles to titlecase.

include:
 - images
 - javascripts
 - stylesheets
exclude:
 - unicorn.rb
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor
